import "../styles/globals.css";
import "bootstrap/dist/css/bootstrap.css";
import React, { useEffect, useState } from "react";
import "../components/layouts/Navbar";
import "../components/layouts/Footer";
import Footer from "../components/layouts/Footer";
import Navbar from "../components/layouts/Navbar";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  const [usrAddr, setUsrAddr] = useState("");
  // to load bootstrap js
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap");
  }, []);

  return (
    <div>
      <Head>
        <title>Inno Bank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bank.ico" />
      </Head>
      <Navbar usrAddr={usrAddr} setUsrAddr={setUsrAddr} />
      <Component {...pageProps} />
      {/* <Footer /> */}
    </div>
  );
}

export default MyApp;
