import "../styles/globals.css";
import "bootstrap/dist/css/bootstrap.css";
import React, { useEffect, useState } from "react";
import "../components/layouts/Navbar";
import "../components/layouts/Footer";
import Footer from "../components/layouts/Footer";
import Navbar from "../components/layouts/Navbar";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  const [usrAddr, setUsrAddr] = useState("");
  const [myContract, setMyContract] = useState("");
  const [current, setCurrent] = useState("home");
  const [con, setCon] = useState(false);

  // to load bootstrap js
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap");
  }, []);

  return (
    <div>
      <Head>
        <title>Inno Bank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bank.ico" />
      </Head>
      <Navbar
        setUsrAddr={setUsrAddr}
        current={current}
        setCurrent={setCurrent}
        setMyContract={setMyContract}
        con={con}
        setCon={setCon}
      />
      <Component {...pageProps} setCurrent={setCurrent} myContract={myContract} />
      {/* <Footer /> */}
    </div>
  );
}

export default MyApp;
